# Generated by Django 3.2.15 on 2022-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('location', models.CharField(choices=[('IN', 'INSIDE SEATING'), ('OUT', 'OUTSIDE SEATING')], max_length=3)),
            ],
        ),
    ]
