# Generated by Django 3.2.15 on 2022-08-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0004_auto_20220816_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None, help_text='DD-MM-YY'),
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '09:00 - 10:30'), (1, '10:30 - 12:00'), (2, '12:00 - 13:30'), (3, '13:30 - 15:00'), (4, '15:00 - 16:30'), (5, '16:30 - 18:00'), (6, '18:00 - 19:30'), (7, '19:30 - 21:00'), (8, '21:00 - 22:30')], default=None),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('table', 'date', 'timeslot')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
    ]
