# Generated by Django 3.2.15 on 2022-08-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0005_auto_20220816_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.IntegerField()),
                ('closing_time', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='table',
            old_name='max_people',
            new_name='no_seats',
        ),
        migrations.RemoveField(
            model_name='table',
            name='min_people',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(default=None, help_text='DD-MM-YYYY'),
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timeslot',
        ),
    ]
