# Generated by Django 3.2.15 on 2022-08-16 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0009_auto_20220816_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date_time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
