# Generated by Django 3.2.15 on 2022-08-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0010_auto_20220816_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningTimes',
        ),
    ]
