# Generated by Django 3.2.15 on 2022-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0011_delete_openingtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SHARERS', 'sharers'), ('PLATTERS', 'platters'), ('SUSHI', 'sushi'), ('LARGE PLATES', 'large plates'), ('DESSERTS', 'desserts')], max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('dietaryinfo', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
