# Generated by Django 3.2.15 on 2022-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0013_auto_20220918_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='dietaryinfo',
            field=models.CharField(max_length=20),
        ),
    ]
