# Generated by Django 3.2.15 on 2022-09-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0015_alter_fooditem_dietaryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.IntegerField(blank=True, max_length=12, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=30, null=True)),
                ('message', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
