# Generated by Django 3.2.15 on 2022-10-05 18:55

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0020_auto_20220926_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
