# Generated by Django 3.2.15 on 2022-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0023_alter_contact_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
