# Generated by Django 3.2.15 on 2022-10-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantbookings', '0024_alter_contact_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date_time_start']},
        ),
    ]
